### ISSUE TITLE
Game score prompt - conditional

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentaur-survivors#30]
Have the game only prompt for a score if it was built with the leaderboard API URL + PSK

**Comment by bitsandfoxes** [comment]
The game now stores the required data for accessing the leaderboard in a config object in `/Resources`. During scene load it checks whether the config is enabled and tries to log in. If it's disabled or the login failed the "post your score" prompt remains hidden.
<img width="273" alt="Screenshot 2024-03-13 at 11 29 59" src="https://github.com/getsentry/sentaur-survivors/assets/25725783/c4f6d274-6552-4ef7-9b80-f1e6f6fd5c08">
